# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "usb_storage" "sd_mod" "sr_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/1b5e4973-8baa-4d3b-b3c0-5e9696e5da6b";
      fsType = "btrfs";
      options = [ "ssd" "compress=zstd:1" "noatime" "subvol=@" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/39B7-18F6";
      fsType = "vfat";
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/1b5e4973-8baa-4d3b-b3c0-5e9696e5da6b";
      fsType = "btrfs";
      options = [ "ssd" "noatime" "compress=zstd:1" "subvol=@home" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/1b5e4973-8baa-4d3b-b3c0-5e9696e5da6b";
      fsType = "btrfs";
      options = [ "ssd" "compress=zstd:1" "noatime" "subvol=@nix" ];
    };

  fileSystems."/bhl" =
    { device = "/dev/disk/by-uuid/1b5e4973-8baa-4d3b-b3c0-5e9696e5da6b";
      fsType = "btrfs";
      options = [ "ssd" "noatime" "nodatacow" "nodatasum" "subvol=@bhl" ];
    };

  fileSystems."/var/lib/postgresql" =
    { device = "/dev/disk/by-uuid/1b5e4973-8baa-4d3b-b3c0-5e9696e5da6b";
      fsType = "btrfs";
      options = [ "ssd" "noatime" "nodatacow" "nodatasum" "subvol=@postgres" ];
    };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp6s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp0s20f3.useDHCP = lib.mkDefault true;

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
